### ISSUE TITLE
Meta: TODO Breakout

### ISSUE THREAD

**Issue by awwad** [uptane/obsolete-reference-implementation#104]
Uptane TODOs:

- [ ] ASN.1 delegations    (testing first, then support if it's missing) (#103)
- [ ] ASN.1 multi-key        (testing first, then support, which is missing) (#102)
- [ ] TUF: integration testing   (basically the compliance testing code + wrapping)
- [ ] Uptane: integration testing  (basically the compliance testing code + wrapping)
- [ ] TUF: Compliance testing per se (includes harness and documentation)
- [ ] Uptane: Compliance testing per se (includes harness and documentation) (#65)
- [ ] hardware ids (#5)
- [ ] release counters (also #5)
- [ ] image encryption (#34)
- [ ] Investigate these potential race conditions in demo code between Primary and Secondary leading to delays / having to skip update cycles: #92, #93
- [ ] CONSIDER arbitrary custom fileinfo support (#37)
